name: CI
on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}
env:
  DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
  APPNAME_SHORT: waifu2x
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.0.3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64
      - name: install Python packages
        run: |
          pip install build
      - name: build
        run: |
          python -m build -w .
  ubuntu:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv libvulkan-dev swig
          pip install build
      - name: build
        run: |
          python -m build -w .
  ubuntu-1804:
    runs-on: ubuntu-18.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install dependencies
        run: |
          apt-get update
          apt-get install -y python3-pip python3-venv libvulkan-dev swig
          pip install build
      - name: build
        run: |
          python -m build -w .
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v1
        with:
          path: vulkansdk-macos-1.2.162.0
          key: vulkansdk-macos-1.2.162.0
      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.2.162.0/mac/vulkansdk-macos-1.2.162.0.dmg?Human=true -O vulkansdk-macos-1.2.162.0.dmg
          hdiutil attach vulkansdk-macos-1.2.162.0.dmg
          cp -r /Volumes/vulkansdk-macos-1.2.162.0 .
          rm -rf vulkansdk-macos-1.2.162.0/Applications
          find vulkansdk-macos-1.2.162.0 -type f | grep -v -E 'vulkan|glslang|MoltenVK' | xargs rm
          hdiutil detach /Volumes/vulkansdk-macos-1.2.162.0
      - name: install-swig
        run: brew install swig
      - name: build-x86_64
        run: |
          export VULKAN_SDK=`pwd`/vulkansdk-macos-1.2.162.0/macOS
          mkdir build-x86_64 && cd build-x86_64
          cmake -DUSE_STATIC_MOLTENVK=ON -DCMAKE_OSX_ARCHITECTURES="x86_64" \
              -DVulkan_INCLUDE_DIR=`pwd`/../vulkansdk-macos-1.2.162.0/MoltenVK/include \
              -DVulkan_LIBRARY=`pwd`/../vulkansdk-macos-1.2.162.0/MoltenVK/MoltenVK.xcframework/macos-arm64_x86_64/libMoltenVK.a \
              ../${{ env.APPNAME_SHORT }}_ncnn_vulkan_python
          cmake --build . -j 3
